import mongoose from 'mongoose'
import dotenv from 'dotenv'
import Hospital from './models/Hospital.js'
import User from './models/User.js'

dotenv.config()

const seedHospitals = async () => {
  await mongoose.connect(process.env.MONGO_URI)
  console.log('Connected to Atlas')

  // get your superadmin user to use as submittedBy
  const admin = await User.findOne({ role: 'superadmin' })
  if (!admin) {
    console.log('No superadmin found — register and set role first')
    process.exit(1)
  }

  await Hospital.deleteMany()
  console.log('Cleared existing hospitals')

  const hospitals = [
    {
      name: 'Ganga Hospital',
      address: '313 Mettupalayam Rd, Coimbatore 641043',
      phone: '0422-2485000',
      coverImage:
        'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.9558, 11.0168] },
      categories: ['Orthopaedic', 'Surgery', 'Emergency', 'General'],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.5,
      ratingCount: 230,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'PSG Hospitals',
      address: 'Peelamedu, Coimbatore 641004',
      phone: '0422-4345000',
      coverImage:
        'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [77.0066, 11.0267] },
      categories: ['Paediatric', 'General', 'Surgery', 'Neurology'],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.6,
      ratingCount: 412,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Kovai Medical Center (KMCH)',
      address: 'Avanashi Rd, Coimbatore 641014',
      phone: '0422-4323800',
      coverImage:
        'https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [77.04, 11.035] },
      categories: [
        'Paediatric',
        'General',
        'Emergency',
        'Surgery',
        'Neurology',
      ],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.7,
      ratingCount: 589,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Sri Ramakrishna Hospital',
      address: '395 Sarojini Naidu Rd, Coimbatore 641044',
      phone: '0422-4500000',
      coverImage:
        'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.9726, 11.005] },
      categories: ['General', 'Surgery', 'Paediatric', 'Orthopaedic'],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.4,
      ratingCount: 321,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Aravind Eye Hospital',
      address: 'Avinashi Rd, Coimbatore 641014',
      phone: '0422-4360000',
      coverImage:
        'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [77.035, 11.031] },
      categories: ['General', 'Surgery'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.8,
      ratingCount: 670,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '08:00', closeTime: '17:00', isOpen: true },
        { day: 'Tuesday', openTime: '08:00', closeTime: '17:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '08:00',
          closeTime: '17:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '08:00',
          closeTime: '17:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '08:00', closeTime: '17:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '08:00',
          closeTime: '13:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'G. Kuppuswamy Naidu Memorial Hospital',
      address: 'Pappanaickenpalayam, Coimbatore 641037',
      phone: '0422-2212777',
      coverImage:
        'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.98, 11.045] },
      categories: ['General', 'Paediatric', 'Surgery', 'Emergency'],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.3,
      ratingCount: 198,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Sugam Hospital',
      address: 'Gandhipuram, Coimbatore 641012',
      phone: '0422-2525252',
      coverImage:
        'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.9629, 11.0168] },
      categories: ['General', 'Paediatric', 'ENT'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.1,
      ratingCount: 143,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '09:00', closeTime: '21:00', isOpen: true },
        { day: 'Tuesday', openTime: '09:00', closeTime: '21:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '09:00',
          closeTime: '21:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '09:00',
          closeTime: '21:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '09:00', closeTime: '21:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '09:00',
          closeTime: '18:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'Lotus Eye Hospital',
      address: 'RS Puram, Coimbatore 641002',
      phone: '0422-2547400',
      coverImage:
        'https://images.unsplash.com/photo-1551076805-e1869033e561?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.9558, 11.005] },
      categories: ['Surgery', 'General'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.5,
      ratingCount: 267,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '09:00', closeTime: '18:00', isOpen: true },
        { day: 'Tuesday', openTime: '09:00', closeTime: '18:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '09:00',
          closeTime: '18:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '09:00',
          closeTime: '18:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '09:00', closeTime: '18:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '09:00',
          closeTime: '13:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'Coimbatore Medical College Hospital',
      address: 'Trichy Rd, Coimbatore 641018',
      phone: '0422-2301393',
      coverImage:
        'https://images.unsplash.com/photo-1504439468489-c8920d796a29?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.99, 10.995] },
      categories: [
        'General',
        'Paediatric',
        'Emergency',
        'Surgery',
        'Neurology',
        'Orthopaedic',
      ],
      is24x7: true,
      isEmergency: true,
      avgRating: 3.9,
      ratingCount: 534,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'KG Hospital',
      address: 'Arts College Rd, Coimbatore 641018',
      phone: '0422-2212911',
      coverImage:
        'https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.98, 11.01] },
      categories: [
        'General',
        'Paediatric',
        'Surgery',
        'Orthopaedic',
        'Emergency',
      ],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.2,
      ratingCount: 389,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Sabari Hospital',
      address: 'Saibaba Colony, Coimbatore 641011',
      phone: '0422-2444100',
      coverImage:
        'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.95, 11.025] },
      categories: ['General', 'Paediatric', 'ENT'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.0,
      ratingCount: 112,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '08:30', closeTime: '20:30', isOpen: true },
        { day: 'Tuesday', openTime: '08:30', closeTime: '20:30', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '08:30',
          closeTime: '20:30',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '08:30',
          closeTime: '20:30',
          isOpen: true,
        },
        { day: 'Friday', openTime: '08:30', closeTime: '20:30', isOpen: true },
        {
          day: 'Saturday',
          openTime: '08:30',
          closeTime: '14:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'Vivekananda Hospital',
      address: 'Singanallur, Coimbatore 641005',
      phone: '0422-2572222',
      coverImage:
        'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [77.02, 10.998] },
      categories: ['General', 'Surgery', 'Paediatric'],
      is24x7: false,
      isEmergency: true,
      avgRating: 4.1,
      ratingCount: 167,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '08:00', closeTime: '21:00', isOpen: true },
        { day: 'Tuesday', openTime: '08:00', closeTime: '21:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '08:00',
          closeTime: '21:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '08:00',
          closeTime: '21:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '08:00', closeTime: '21:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '08:00',
          closeTime: '18:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '10:00', closeTime: '14:00', isOpen: true },
      ],
    },
    {
      name: 'Meenakshi Mission Hospital',
      address: 'Vadavalli, Coimbatore 641041',
      phone: '0422-2691234',
      coverImage:
        'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.92, 11.015] },
      categories: ['General', 'Paediatric', 'Dermatology'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.2,
      ratingCount: 134,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '09:00', closeTime: '20:00', isOpen: true },
        { day: 'Tuesday', openTime: '09:00', closeTime: '20:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '09:00',
          closeTime: '20:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '09:00',
          closeTime: '20:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '09:00', closeTime: '20:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '09:00',
          closeTime: '15:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'Rathnavel Subramaniam Hospital',
      address: 'RS Puram, Coimbatore 641002',
      phone: '0422-2545454',
      coverImage:
        'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.953, 11.002] },
      categories: ['General', 'Surgery', 'ENT', 'Orthopaedic'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.0,
      ratingCount: 98,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '09:00', closeTime: '19:00', isOpen: true },
        { day: 'Tuesday', openTime: '09:00', closeTime: '19:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '09:00',
          closeTime: '19:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '09:00',
          closeTime: '19:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '09:00', closeTime: '19:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '09:00',
          closeTime: '13:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'Tiruppur Child Care Hospital',
      address: 'Tiruppur Rd, Coimbatore 641687',
      phone: '0421-2234567',
      coverImage:
        'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [77.341, 11.1075] },
      categories: ['Paediatric', 'General', 'ENT'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.3,
      ratingCount: 87,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '09:00', closeTime: '20:00', isOpen: true },
        { day: 'Tuesday', openTime: '09:00', closeTime: '20:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '09:00',
          closeTime: '20:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '09:00',
          closeTime: '20:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '09:00', closeTime: '20:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '09:00',
          closeTime: '15:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'SNR Sons Charity Hospital',
      address: 'Coimbatore 641045',
      phone: '0422-2393939',
      coverImage:
        'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.965, 11.035] },
      categories: ['General', 'Surgery', 'Paediatric'],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.1,
      ratingCount: 156,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Daya Hospital',
      address: 'Trichy Rd, Singanallur, Coimbatore 641005',
      phone: '0422-4399999',
      coverImage:
        'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [77.018, 10.996] },
      categories: ['General', 'Paediatric', 'Orthopaedic', 'Surgery'],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.3,
      ratingCount: 203,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Karpagam Faculty of Medical Sciences',
      address: 'Othakkalmandapam, Coimbatore 641032',
      phone: '0422-2611500',
      coverImage:
        'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.91, 11.005] },
      categories: [
        'General',
        'Paediatric',
        'Surgery',
        'Emergency',
        'Neurology',
      ],
      is24x7: true,
      isEmergency: true,
      avgRating: 4.0,
      ratingCount: 178,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        { day: 'Tuesday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Friday', openTime: '00:00', closeTime: '23:59', isOpen: true },
        {
          day: 'Saturday',
          openTime: '00:00',
          closeTime: '23:59',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '23:59', isOpen: true },
      ],
    },
    {
      name: 'Skin Care Clinic',
      address: 'Race Course, Coimbatore 641018',
      phone: '0422-2220022',
      coverImage:
        'https://images.unsplash.com/photo-1629909615184-74f495363b67?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.975, 11.012] },
      categories: ['Dermatology', 'General'],
      is24x7: false,
      isEmergency: false,
      avgRating: 4.4,
      ratingCount: 89,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '10:00', closeTime: '19:00', isOpen: true },
        { day: 'Tuesday', openTime: '10:00', closeTime: '19:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '10:00',
          closeTime: '19:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '10:00',
          closeTime: '19:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '10:00', closeTime: '19:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '10:00',
          closeTime: '14:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
    {
      name: 'Neuro Care Hospital',
      address: 'Gandhipuram, Coimbatore 641012',
      phone: '0422-2323232',
      coverImage:
        'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [76.961, 11.019] },
      categories: ['Neurology', 'General', 'Surgery'],
      is24x7: false,
      isEmergency: true,
      avgRating: 4.5,
      ratingCount: 145,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '09:00', closeTime: '21:00', isOpen: true },
        { day: 'Tuesday', openTime: '09:00', closeTime: '21:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '09:00',
          closeTime: '21:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '09:00',
          closeTime: '21:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '09:00', closeTime: '21:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '09:00',
          closeTime: '17:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '10:00', closeTime: '14:00', isOpen: true },
      ],
    },
    {
      name: 'Ortho One Hospital',
      address: 'Avinashi Rd, Coimbatore 641014',
      phone: '0422-4646464',
      coverImage:
        'https://images.unsplash.com/photo-1504439468489-c8920d796a29?w=800&h=400&fit=crop',
      location: { type: 'Point', coordinates: [77.028, 11.029] },
      categories: ['Orthopaedic', 'Surgery', 'Emergency'],
      is24x7: false,
      isEmergency: true,
      avgRating: 4.6,
      ratingCount: 312,
      status: 'approved',
      submittedBy: admin._id,
      approvedAt: new Date(),
      operatingHours: [
        { day: 'Monday', openTime: '08:00', closeTime: '20:00', isOpen: true },
        { day: 'Tuesday', openTime: '08:00', closeTime: '20:00', isOpen: true },
        {
          day: 'Wednesday',
          openTime: '08:00',
          closeTime: '20:00',
          isOpen: true,
        },
        {
          day: 'Thursday',
          openTime: '08:00',
          closeTime: '20:00',
          isOpen: true,
        },
        { day: 'Friday', openTime: '08:00', closeTime: '20:00', isOpen: true },
        {
          day: 'Saturday',
          openTime: '08:00',
          closeTime: '14:00',
          isOpen: true,
        },
        { day: 'Sunday', openTime: '00:00', closeTime: '00:00', isOpen: false },
      ],
    },
  ]

  await Hospital.insertMany(hospitals)
  console.log(`${hospitals.length} hospitals seeded successfully`)
  process.exit(0)
}

seedHospitals().catch((err) => {
  console.error(err)
  process.exit(1)
})
